version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/main/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "nmalinowski"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
